# Generated by Django 5.1.5 on 2025-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to=''),
        ),
    ]
