# Generated by Django 5.1.5 on 2025-02-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-avatar.png', null=True, upload_to='media/'),
        ),
    ]
